name: Publish Docker image
on:
  release:
    types: [released]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2     

      - name: Set Short SHA
        id: vars
        run: echo "::set-output name=sha_short::sha-$(git rev-parse --short HEAD)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/xelatex-docker
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=latest
            type=raw,value=${{ steps.vars.outputs.sha_short }}
          labels: |
            tags=${{ github.ref_name }},latest,${{ steps.vars.outputs.sha_short }}
            org.opencontainers.image.description=xelatex-docker

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
